set_clock_groups -name async_clock_group -asynchronous -group [get_clocks -of_objects [get_pins mb_subsystem_i/mig_7series_0/u_mb_subsystem_mig_7series_0_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -group [get_clocks [list [get_clocks -of_objects [get_pins mb_subsystem_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT2]] [get_clocks -of_objects [get_pins mb_subsystem_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT2B]]]] -group [get_clocks -of_objects [get_pins mb_subsystem_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins mb_subsystem_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks -regexp -nocase .*mmcm_ps_clk.*]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
