
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_p2h]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[0]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[7]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[2]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[7]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[8]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[15]}]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/i_slave_fifo_full_n]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_adcclk]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_cdsclk2]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_p1h]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_slave_fifo_data_valid_n]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[5]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[1]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[3]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[13]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[14]}]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/i_slave_fifo_empty_n]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_cdsclk1]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_p1v]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_p2v_tg]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_slave_fifo_clk]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[1]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[2]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[3]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[6]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[0]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[4]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[9]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[11]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[12]}]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_p3h]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_p4h_sg]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_rg]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/i_adc_data[4]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[5]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[6]}]
set_property MARK_DEBUG true [get_nets {mb_subsystem_i/o_slave_fifo_data[10]}]
set_property MARK_DEBUG true [get_nets gpio_tri_i_7]
set_property MARK_DEBUG true [get_nets gpio_tri_i_6]
set_property MARK_DEBUG true [get_nets gpio_tri_i_5]
set_property MARK_DEBUG true [get_nets gpio_tri_i_4]
set_property MARK_DEBUG true [get_nets gpio_tri_i_3]
set_property MARK_DEBUG true [get_nets gpio_tri_i_2]
set_property MARK_DEBUG true [get_nets gpio_tri_i_1]
set_property MARK_DEBUG true [get_nets gpio_tri_i_0]
set_property MARK_DEBUG true [get_nets spi_io0_o]
set_property MARK_DEBUG true [get_nets spi_io1_o]
set_property MARK_DEBUG true [get_nets spi_ss_o_2]
set_property MARK_DEBUG true [get_nets spi_ss_o_1]
set_property MARK_DEBUG true [get_nets spi_ss_o_0]



connect_debug_port u_ila_1/probe1 [get_nets [list gpio_tri_i_1]]
connect_debug_port u_ila_1/probe2 [get_nets [list gpio_tri_i_2]]
connect_debug_port u_ila_1/probe3 [get_nets [list gpio_tri_i_3]]
connect_debug_port u_ila_1/probe6 [get_nets [list mb_subsystem_i/o_slave_fifo_data_valid_n]]
connect_debug_port u_ila_2/probe2 [get_nets [list gpio_tri_i_0]]
connect_debug_port u_ila_2/probe3 [get_nets [list gpio_tri_i_4]]
connect_debug_port u_ila_2/probe4 [get_nets [list gpio_tri_i_5]]
connect_debug_port u_ila_2/probe5 [get_nets [list gpio_tri_i_6]]
connect_debug_port u_ila_2/probe6 [get_nets [list gpio_tri_i_7]]

set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_slave_fifo_data_last_n]
set_property MARK_DEBUG true [get_nets mb_subsystem_i/o_slave_fifo_data_wr_en_n]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mb_subsystem_i/ccd_controller_v1_0_0/inst/ccd_controller_v1_0_S00_AXI_inst/u_ccd_ddr/u_ccd_driver/u_ccd_clk_gen/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {mb_subsystem_i/i_adc_data[0]} {mb_subsystem_i/i_adc_data[1]} {mb_subsystem_i/i_adc_data[2]} {mb_subsystem_i/i_adc_data[3]} {mb_subsystem_i/i_adc_data[4]} {mb_subsystem_i/i_adc_data[5]} {mb_subsystem_i/i_adc_data[6]} {mb_subsystem_i/i_adc_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list mb_subsystem_i/o_cdsclk1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list mb_subsystem_i/o_cdsclk2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list mb_subsystem_i/o_p1h]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list mb_subsystem_i/o_p1v]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list mb_subsystem_i/o_p2h]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list mb_subsystem_i/o_p2v_tg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list mb_subsystem_i/o_p3h]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list mb_subsystem_i/o_p4h_sg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list mb_subsystem_i/o_rg]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list mb_subsystem_i/clk_wiz_0/inst/clk_48M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {mb_subsystem_i/o_slave_fifo_data[0]} {mb_subsystem_i/o_slave_fifo_data[1]} {mb_subsystem_i/o_slave_fifo_data[2]} {mb_subsystem_i/o_slave_fifo_data[3]} {mb_subsystem_i/o_slave_fifo_data[4]} {mb_subsystem_i/o_slave_fifo_data[5]} {mb_subsystem_i/o_slave_fifo_data[6]} {mb_subsystem_i/o_slave_fifo_data[7]} {mb_subsystem_i/o_slave_fifo_data[8]} {mb_subsystem_i/o_slave_fifo_data[9]} {mb_subsystem_i/o_slave_fifo_data[10]} {mb_subsystem_i/o_slave_fifo_data[11]} {mb_subsystem_i/o_slave_fifo_data[12]} {mb_subsystem_i/o_slave_fifo_data[13]} {mb_subsystem_i/o_slave_fifo_data[14]} {mb_subsystem_i/o_slave_fifo_data[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list mb_subsystem_i/i_slave_fifo_empty_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list mb_subsystem_i/i_slave_fifo_full_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list mb_subsystem_i/o_slave_fifo_data_last_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list mb_subsystem_i/o_slave_fifo_data_wr_en_n]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list mb_subsystem_i/clk_wiz_0/inst/clk_100M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 26 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[6]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[7]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[8]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[9]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[10]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[11]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[12]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[13]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[14]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[15]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[16]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[17]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[18]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[19]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[20]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[21]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[22]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[23]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[24]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[25]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[26]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[27]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[28]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[29]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[30]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_AWADDR[31]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 26 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[6]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[7]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[8]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[9]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[10]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[11]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[12]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[13]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[14]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[15]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[16]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[17]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[18]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[19]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[20]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[21]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[22]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[23]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[24]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[25]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[26]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[27]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[28]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[29]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[30]} {mb_subsystem_i/microblaze_0_axi_periph_M03_AXI_ARADDR[31]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list mb_subsystem_i/o_adcclk]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list spi_io0_o]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list spi_io1_o]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list spi_ss_o_0]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list spi_ss_o_1]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
connect_debug_port u_ila_2/probe7 [get_nets [list spi_ss_o_2]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
